version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install --silent --no-progress -g yarn
  pre_build:
    commands:
      - rm -rf .next out node_modules
      - npm install  --silent
      - npm run build
      - npm run export
    

  build:
    commands:
#       - yarn test
      - yarn lint

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'

artifacts:
  files:
    - '**/*'
    
  base-directory: 'out'
