import React from "react";
// components
import AdminNavbar from "@components/atoms/dashboard/navbar";
import Sidebar from "@components/Admin/sidebar/sidebar";
// import HeaderStats from "components/Admin/HeaderStats";
// import FooterAdmin from "@components/Admin/Footers/FooterAdmin";
import Head from "next/head";
import { Toaster } from "react-hot-toast";

export default function dashboardLayout({ children }:any) {
  return (
    <>
     <Head>
        <title>Rakheoana Lefela | Dashboardr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        {/* <link href="https://cdn.lineicons.com/3.0/lineicons.css" rel="stylesheet"></link> */}
        <link
          href="https://cdn.lineicons.com/4.0/lineicons.css"
          rel="stylesheet"
        ></link>
        <script src="https://cdn.tailwindcss.com"></script>
        
      </Head>
      <Toaster position="bottom-left" reverseOrder={false} />
      <Sidebar />
      <div className="relative md:ml-64 bg-blueGray-100">
        <AdminNavbar />
        Header
        {/* <HeaderStats /> */}
        <div className="px-4 md:px-10 mx-auto w-full -m-24">
          {children}
          {/* <FooterAdmin /> */}
        </div>
      </div>
    </>
  );
}
