
import Navbar from '../atoms/navbar'
import Footer from '../atoms/footer'
import Head from 'next/head'

export default function Layout({ children }: any) {
    return (
        <>
            <Head>
                <title>Rakheoana Lefela | software developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Navbar />
            <main>{children}</main>
            <Footer />
        </>
    )
}



